.read  /lakehouse/default/Files/sql/init.sql
.read  /lakehouse/default/Files/sql/schema.sql
.read  /lakehouse/default/Files/sql/download.sql
.read  /lakehouse/default/Files/sql/duid.sql
.read  /lakehouse/default/Files/sql/scada.sql
.read  /lakehouse/default/Files/sql/price.sql
.read  /lakehouse/default/Files/sql/scada_today.sql
.read  /lakehouse/default/Files/sql/price_today.sql
.read  /lakehouse/default/Files/sql/summary.sql
.read  /lakehouse/default/Files/sql/export.sql