CREATE TABLE IF NOT EXISTS price (
    UNIT VARCHAR, REGIONID VARCHAR, VERSION DOUBLE,
    RUNNO DOUBLE, INTERVENTION DOUBLE, RRP DOUBLE,
    EEP DOUBLE, ROP DOUBLE, APCFLAG DOUBLE,
    MARKETSUSPENDEDFLAG DOUBLE, TOTALDEMAND DOUBLE, DEMANDFORECAST DOUBLE,
    DISPATCHABLEGENERATION DOUBLE, DISPATCHABLELOAD DOUBLE, NETINTERCHANGE DOUBLE,
    EXCESSGENERATION DOUBLE, LOWER5MINDISPATCH DOUBLE, LOWER5MINIMPORT DOUBLE,
    LOWER5MINLOCALDISPATCH DOUBLE, LOWER5MINLOCALPRICE DOUBLE, LOWER5MINLOCALREQ DOUBLE,
    LOWER5MINPRICE DOUBLE, LOWER5MINREQ DOUBLE, LOWER5MINSUPPLYPRICE DOUBLE,
    LOWER60SECDISPATCH DOUBLE, LOWER60SECIMPORT DOUBLE, LOWER60SECLOCALDISPATCH DOUBLE,
    LOWER60SECLOCALPRICE DOUBLE, LOWER60SECLOCALREQ DOUBLE, LOWER60SECPRICE DOUBLE,
    LOWER60SECREQ DOUBLE, LOWER60SECSUPPLYPRICE DOUBLE, LOWER6SECDISPATCH DOUBLE,
    LOWER6SECIMPORT DOUBLE, LOWER6SECLOCALDISPATCH DOUBLE, LOWER6SECLOCALPRICE DOUBLE,
    LOWER6SECLOCALREQ DOUBLE, LOWER6SECPRICE DOUBLE, LOWER6SECREQ DOUBLE,
    LOWER6SECSUPPLYPRICE DOUBLE, RAISE5MINDISPATCH DOUBLE, RAISE5MINIMPORT DOUBLE,
    RAISE5MINLOCALDISPATCH DOUBLE, RAISE5MINLOCALPRICE DOUBLE, RAISE5MINLOCALREQ DOUBLE,
    RAISE5MINPRICE DOUBLE, RAISE5MINREQ DOUBLE, RAISE5MINSUPPLYPRICE DOUBLE,
    RAISE60SECDISPATCH DOUBLE, RAISE60SECIMPORT DOUBLE, RAISE60SECLOCALDISPATCH DOUBLE,
    RAISE60SECLOCALPRICE DOUBLE, RAISE60SECLOCALREQ DOUBLE, RAISE60SECPRICE DOUBLE,
    RAISE60SECREQ DOUBLE, RAISE60SECSUPPLYPRICE DOUBLE, RAISE6SECDISPATCH DOUBLE,
    RAISE6SECIMPORT DOUBLE, RAISE6SECLOCALDISPATCH DOUBLE, RAISE6SECLOCALPRICE DOUBLE,
    RAISE6SECLOCALREQ DOUBLE, RAISE6SECPRICE DOUBLE, RAISE6SECREQ DOUBLE,
    RAISE6SECSUPPLYPRICE DOUBLE, AGGREGATEDISPATCHERROR DOUBLE, AVAILABLEGENERATION DOUBLE,
    AVAILABLELOAD DOUBLE, INITIALSUPPLY DOUBLE, CLEAREDSUPPLY DOUBLE,
    LOWERREGIMPORT DOUBLE, LOWERREGLOCALDISPATCH DOUBLE, LOWERREGLOCALREQ DOUBLE,
    LOWERREGREQ DOUBLE, RAISEREGIMPORT DOUBLE, RAISEREGLOCALDISPATCH DOUBLE,
    RAISEREGLOCALREQ DOUBLE, RAISEREGREQ DOUBLE, RAISE5MINLOCALVIOLATION DOUBLE,
    RAISEREGLOCALVIOLATION DOUBLE, RAISE60SECLOCALVIOLATION DOUBLE, RAISE6SECLOCALVIOLATION DOUBLE,
    LOWER5MINLOCALVIOLATION DOUBLE, LOWERREGLOCALVIOLATION DOUBLE, LOWER60SECLOCALVIOLATION DOUBLE,
    LOWER6SECLOCALVIOLATION DOUBLE, RAISE5MINVIOLATION DOUBLE, RAISEREGVIOLATION DOUBLE,
    RAISE60SECVIOLATION DOUBLE, RAISE6SECVIOLATION DOUBLE, LOWER5MINVIOLATION DOUBLE,
    LOWERREGVIOLATION DOUBLE, LOWER60SECVIOLATION DOUBLE, LOWER6SECVIOLATION DOUBLE,
    RAISE6SECRRP DOUBLE, RAISE6SECROP DOUBLE, RAISE6SECAPCFLAG DOUBLE,
    RAISE60SECRRP DOUBLE, RAISE60SECROP DOUBLE, RAISE60SECAPCFLAG DOUBLE,
    RAISE5MINRRP DOUBLE, RAISE5MINROP DOUBLE, RAISE5MINAPCFLAG DOUBLE,
    RAISEREGRRP DOUBLE, RAISEREGROP DOUBLE, RAISEREGAPCFLAG DOUBLE,
    LOWER6SECRRP DOUBLE, LOWER6SECROP DOUBLE, LOWER6SECAPCFLAG DOUBLE,
    LOWER60SECRRP DOUBLE, LOWER60SECROP DOUBLE, LOWER60SECAPCFLAG DOUBLE,
    LOWER5MINRRP DOUBLE, LOWER5MINROP DOUBLE, LOWER5MINAPCFLAG DOUBLE,
    LOWERREGRRP DOUBLE, LOWERREGROP DOUBLE, LOWERREGAPCFLAG DOUBLE,
    RAISE6SECACTUALAVAILABILITY DOUBLE, RAISE60SECACTUALAVAILABILITY DOUBLE, RAISE5MINACTUALAVAILABILITY DOUBLE,
    RAISEREGACTUALAVAILABILITY DOUBLE, LOWER6SECACTUALAVAILABILITY DOUBLE, LOWER60SECACTUALAVAILABILITY DOUBLE,
    LOWER5MINACTUALAVAILABILITY DOUBLE, LOWERREGACTUALAVAILABILITY DOUBLE, LORSURPLUS DOUBLE,
    LRCSURPLUS DOUBLE, file VARCHAR, SETTLEMENTDATE TIMESTAMP,
    DATE DATE, YEAR SMALLINT
);

ALTER TABLE if exists price       SET PARTITIONED BY (YEAR);

SET VARIABLE list_of_files_price = (
                                            WITH xxxx AS (
                                               SELECT
                                                concat('/lakehouse/default/Files/', extracted_filepath) AS file
                                                FROM '{source}'
                                                WHERE parse_filename(extracted_filepath) NOT IN (SELECT DISTINCT file FROM price)
                                                ORDER BY file
                                                LIMIT {Nbr_Files_to_Process}
                                                   )
                                                SELECT list(file) FROM xxxx );


                                            
insert into price BY NAME
WITH raw AS (
    FROM read_csv(
        getvariable('list_of_files_price'),
        skip = 1,
        header = 0,
        all_varchar = 1,
        hive_partitioning = false ,
  columns={{
  'I': 'VARCHAR','UNIT': 'VARCHAR','XX': 'VARCHAR','VERSION': 'VARCHAR','SETTLEMENTDATE': 'VARCHAR','RUNNO': 'VARCHAR',
  'REGIONID': 'VARCHAR','INTERVENTION': 'VARCHAR','RRP': 'VARCHAR','EEP': 'VARCHAR','ROP': 'VARCHAR','APCFLAG': 'VARCHAR',
  'MARKETSUSPENDEDFLAG': 'VARCHAR','TOTALDEMAND': 'VARCHAR','DEMANDFORECAST': 'VARCHAR','DISPATCHABLEGENERATION': 'VARCHAR',
  'DISPATCHABLELOAD': 'VARCHAR','NETINTERCHANGE': 'VARCHAR','EXCESSGENERATION': 'VARCHAR','LOWER5MINDISPATCH': 'VARCHAR',
  'LOWER5MINIMPORT': 'VARCHAR','LOWER5MINLOCALDISPATCH': 'VARCHAR','LOWER5MINLOCALPRICE': 'VARCHAR','LOWER5MINLOCALREQ': 'VARCHAR',
  'LOWER5MINPRICE': 'VARCHAR','LOWER5MINREQ': 'VARCHAR','LOWER5MINSUPPLYPRICE': 'VARCHAR','LOWER60SECDISPATCH': 'VARCHAR','LOWER60SECIMPORT': 'VARCHAR',
  'LOWER60SECLOCALDISPATCH': 'VARCHAR','LOWER60SECLOCALPRICE': 'VARCHAR','LOWER60SECLOCALREQ': 'VARCHAR','LOWER60SECPRICE': 'VARCHAR',
  'LOWER60SECREQ': 'VARCHAR','LOWER60SECSUPPLYPRICE': 'VARCHAR','LOWER6SECDISPATCH': 'VARCHAR','LOWER6SECIMPORT': 'VARCHAR',
  'LOWER6SECLOCALDISPATCH': 'VARCHAR','LOWER6SECLOCALPRICE': 'VARCHAR','LOWER6SECLOCALREQ': 'VARCHAR','LOWER6SECPRICE': 'VARCHAR',
  'LOWER6SECREQ': 'VARCHAR','LOWER6SECSUPPLYPRICE': 'VARCHAR','RAISE5MINDISPATCH': 'VARCHAR','RAISE5MINIMPORT': 'VARCHAR',
  'RAISE5MINLOCALDISPATCH': 'VARCHAR','RAISE5MINLOCALPRICE': 'VARCHAR','RAISE5MINLOCALREQ': 'VARCHAR','RAISE5MINPRICE': 'VARCHAR',
  'RAISE5MINREQ': 'VARCHAR','RAISE5MINSUPPLYPRICE': 'VARCHAR','RAISE60SECDISPATCH': 'VARCHAR','RAISE60SECIMPORT': 'VARCHAR',
  'RAISE60SECLOCALDISPATCH': 'VARCHAR','RAISE60SECLOCALPRICE': 'VARCHAR','RAISE60SECLOCALREQ': 'VARCHAR','RAISE60SECPRICE': 'VARCHAR',
  'RAISE60SECREQ': 'VARCHAR','RAISE60SECSUPPLYPRICE': 'VARCHAR','RAISE6SECDISPATCH': 'VARCHAR','RAISE6SECIMPORT': 'VARCHAR',
  'RAISE6SECLOCALDISPATCH': 'VARCHAR','RAISE6SECLOCALPRICE': 'VARCHAR','RAISE6SECLOCALREQ': 'VARCHAR','RAISE6SECPRICE': 'VARCHAR',
  'RAISE6SECREQ': 'VARCHAR','RAISE6SECSUPPLYPRICE': 'VARCHAR','AGGREGATEDISPATCHERROR': 'VARCHAR','AVAILABLEGENERATION': 'VARCHAR',
  'AVAILABLELOAD': 'VARCHAR','INITIALSUPPLY': 'VARCHAR','CLEAREDSUPPLY': 'VARCHAR','LOWERREGIMPORT': 'VARCHAR','LOWERREGLOCALDISPATCH': 'VARCHAR',
  'LOWERREGLOCALREQ': 'VARCHAR','LOWERREGREQ': 'VARCHAR','RAISEREGIMPORT': 'VARCHAR','RAISEREGLOCALDISPATCH': 'VARCHAR','RAISEREGLOCALREQ': 'VARCHAR',
  'RAISEREGREQ': 'VARCHAR','RAISE5MINLOCALVIOLATION': 'VARCHAR','RAISEREGLOCALVIOLATION': 'VARCHAR','RAISE60SECLOCALVIOLATION': 'VARCHAR',
  'RAISE6SECLOCALVIOLATION': 'VARCHAR','LOWER5MINLOCALVIOLATION': 'VARCHAR','LOWERREGLOCALVIOLATION': 'VARCHAR','LOWER60SECLOCALVIOLATION': 'VARCHAR',
  'LOWER6SECLOCALVIOLATION': 'VARCHAR','RAISE5MINVIOLATION': 'VARCHAR','RAISEREGVIOLATION': 'VARCHAR','RAISE60SECVIOLATION': 'VARCHAR',
  'RAISE6SECVIOLATION': 'VARCHAR','LOWER5MINVIOLATION': 'VARCHAR','LOWERREGVIOLATION': 'VARCHAR','LOWER60SECVIOLATION': 'VARCHAR',
  'LOWER6SECVIOLATION': 'VARCHAR','RAISE6SECRRP': 'VARCHAR','RAISE6SECROP': 'VARCHAR','RAISE6SECAPCFLAG': 'VARCHAR','RAISE60SECRRP': 'VARCHAR',
  'RAISE60SECROP': 'VARCHAR','RAISE60SECAPCFLAG': 'VARCHAR','RAISE5MINRRP': 'VARCHAR','RAISE5MINROP': 'VARCHAR','RAISE5MINAPCFLAG': 'VARCHAR',
  'RAISEREGRRP': 'VARCHAR','RAISEREGROP': 'VARCHAR','RAISEREGAPCFLAG': 'VARCHAR','LOWER6SECRRP': 'VARCHAR','LOWER6SECROP': 'VARCHAR',
  'LOWER6SECAPCFLAG': 'VARCHAR','LOWER60SECRRP': 'VARCHAR','LOWER60SECROP': 'VARCHAR','LOWER60SECAPCFLAG': 'VARCHAR','LOWER5MINRRP': 'VARCHAR',
  'LOWER5MINROP': 'VARCHAR','LOWER5MINAPCFLAG': 'VARCHAR','LOWERREGRRP': 'VARCHAR','LOWERREGROP': 'VARCHAR','LOWERREGAPCFLAG': 'VARCHAR',
  'RAISE6SECACTUALAVAILABILITY': 'VARCHAR','RAISE60SECACTUALAVAILABILITY': 'VARCHAR','RAISE5MINACTUALAVAILABILITY': 'VARCHAR',
  'RAISEREGACTUALAVAILABILITY': 'VARCHAR','LOWER6SECACTUALAVAILABILITY': 'VARCHAR','LOWER60SECACTUALAVAILABILITY': 'VARCHAR',
  'LOWER5MINACTUALAVAILABILITY': 'VARCHAR','LOWERREGACTUALAVAILABILITY': 'VARCHAR','LORSURPLUS': 'VARCHAR','LRCSURPLUS': 'VARCHAR',
  }},
  filename =1,null_padding = true,ignore_errors=1,auto_detect=false)
  where I='D' and UNIT ='DREGION' AND VERSION = 3
                  )
    select
    UNIT,
    REGIONID,
    cast(columns(*exclude(REGIONID,UNIT,SETTLEMENTDATE,I,XX,filename)) as double),
    parse_filename(filename) as file,
    cast (SETTLEMENTDATE as TIMESTAMP) as SETTLEMENTDATE,
    cast(SETTLEMENTDATE as date) as DATE,
	  cast(year (cast (SETTLEMENTDATE as timestamp)) AS INT16) as YEAR
    from raw