CREATE TABLE IF NOT EXISTS scada (
    UNIT VARCHAR, DUID VARCHAR, VERSION DOUBLE,
    RUNNO DOUBLE, INTERVENTION DOUBLE, DISPATCHMODE DOUBLE,
    AGCSTATUS DOUBLE, INITIALMW DOUBLE, TOTALCLEARED DOUBLE,
    RAMPDOWNRATE DOUBLE, RAMPUPRATE DOUBLE, LOWER5MIN DOUBLE,
    LOWER60SEC DOUBLE, LOWER6SEC DOUBLE, RAISE5MIN DOUBLE,
    RAISE60SEC DOUBLE, RAISE6SEC DOUBLE, MARGINAL5MINVALUE DOUBLE,
    MARGINAL60SECVALUE DOUBLE, MARGINAL6SECVALUE DOUBLE, MARGINALVALUE DOUBLE,
    VIOLATION5MINDEGREE DOUBLE, VIOLATION60SECDEGREE DOUBLE, VIOLATION6SECDEGREE DOUBLE,
    VIOLATIONDEGREE DOUBLE, LOWERREG DOUBLE, RAISEREG DOUBLE,
    AVAILABILITY DOUBLE, RAISE6SECFLAGS DOUBLE, RAISE60SECFLAGS DOUBLE,
    RAISE5MINFLAGS DOUBLE, RAISEREGFLAGS DOUBLE, LOWER6SECFLAGS DOUBLE,
    LOWER60SECFLAGS DOUBLE, LOWER5MINFLAGS DOUBLE, LOWERREGFLAGS DOUBLE,
    RAISEREGAVAILABILITY DOUBLE, RAISEREGENABLEMENTMAX DOUBLE, RAISEREGENABLEMENTMIN DOUBLE,
    LOWERREGAVAILABILITY DOUBLE, LOWERREGENABLEMENTMAX DOUBLE, LOWERREGENABLEMENTMIN DOUBLE,
    RAISE6SECACTUALAVAILABILITY DOUBLE, RAISE60SECACTUALAVAILABILITY DOUBLE, RAISE5MINACTUALAVAILABILITY DOUBLE,
    RAISEREGACTUALAVAILABILITY DOUBLE, LOWER6SECACTUALAVAILABILITY DOUBLE, LOWER60SECACTUALAVAILABILITY DOUBLE,
    LOWER5MINACTUALAVAILABILITY DOUBLE, LOWERREGACTUALAVAILABILITY DOUBLE,
    file VARCHAR, SETTLEMENTDATE TIMESTAMP, DATE DATE,
    YEAR SMALLINT
);

ALTER TABLE if exists scada       SET PARTITIONED BY (YEAR);

SET VARIABLE list_of_files_scada = (
                                            WITH xxxx AS (
                                               SELECT
                                                concat('/lakehouse/default/Files/', extracted_filepath) AS file
                                                FROM '{source}'
                                                WHERE parse_filename(extracted_filepath) NOT IN (SELECT DISTINCT file FROM scada)
                                                ORDER BY file
                                                LIMIT {Nbr_Files_to_Process}
                                                   )
                                                SELECT list(file) FROM xxxx );
insert into scada by name
WITH raw AS (
    FROM read_csv(
        getvariable('list_of_files_scada'),
        skip = 1,
        header = 0,
        all_varchar = 1,
        hive_partitioning = false ,
        columns = {{
            'I': 'VARCHAR', 'UNIT': 'VARCHAR', 'XX': 'VARCHAR', 'VERSION': 'VARCHAR',
            'SETTLEMENTDATE': 'VARCHAR', 'RUNNO': 'VARCHAR', 'DUID': 'VARCHAR', 'INTERVENTION': 'VARCHAR',
            'DISPATCHMODE': 'VARCHAR', 'AGCSTATUS': 'VARCHAR', 'INITIALMW': 'VARCHAR', 'TOTALCLEARED': 'VARCHAR',
            'RAMPDOWNRATE': 'VARCHAR', 'RAMPUPRATE': 'VARCHAR', 'LOWER5MIN': 'VARCHAR', 'LOWER60SEC': 'VARCHAR',
            'LOWER6SEC': 'VARCHAR', 'RAISE5MIN': 'VARCHAR', 'RAISE60SEC': 'VARCHAR', 'RAISE6SEC': 'VARCHAR',
            'MARGINAL5MINVALUE': 'VARCHAR', 'MARGINAL60SECVALUE': 'VARCHAR', 'MARGINAL6SECVALUE': 'VARCHAR', 'MARGINALVALUE': 'VARCHAR',
            'VIOLATION5MINDEGREE': 'VARCHAR', 'VIOLATION60SECDEGREE': 'VARCHAR', 'VIOLATION6SECDEGREE': 'VARCHAR', 'VIOLATIONDEGREE': 'VARCHAR',
            'LOWERREG': 'VARCHAR', 'RAISEREG': 'VARCHAR', 'AVAILABILITY': 'VARCHAR', 'RAISE6SECFLAGS': 'VARCHAR',
            'RAISE60SECFLAGS': 'VARCHAR', 'RAISE5MINFLAGS': 'VARCHAR', 'RAISEREGFLAGS': 'VARCHAR', 'LOWER6SECFLAGS': 'VARCHAR',
            'LOWER60SECFLAGS': 'VARCHAR', 'LOWER5MINFLAGS': 'VARCHAR', 'LOWERREGFLAGS': 'VARCHAR', 'RAISEREGAVAILABILITY': 'VARCHAR',
            'RAISEREGENABLEMENTMAX': 'VARCHAR', 'RAISEREGENABLEMENTMIN': 'VARCHAR', 'LOWERREGAVAILABILITY': 'VARCHAR', 'LOWERREGENABLEMENTMAX': 'VARCHAR',
            'LOWERREGENABLEMENTMIN': 'VARCHAR', 'RAISE6SECACTUALAVAILABILITY': 'VARCHAR', 'RAISE60SECACTUALAVAILABILITY': 'VARCHAR', 'RAISE5MINACTUALAVAILABILITY': 'VARCHAR',
            'RAISEREGACTUALAVAILABILITY': 'VARCHAR', 'LOWER6SECACTUALAVAILABILITY': 'VARCHAR', 'LOWER60SECACTUALAVAILABILITY': 'VARCHAR', 'LOWER5MINACTUALAVAILABILITY': 'VARCHAR',
            'LOWERREGACTUALAVAILABILITY': 'VARCHAR'
        }},
        filename = 1,
        null_padding = true,
        ignore_errors = 1,
        auto_detect = false
    )
    WHERE
        I = 'D'
        AND UNIT = 'DUNIT'
        AND VERSION = 3
)
SELECT
    UNIT,
    DUID,
    CAST(columns(* EXCLUDE (DUID, UNIT, SETTLEMENTDATE, I, XX, filename)) AS DOUBLE),
    parse_filename(filename) AS file,
    CAST(SETTLEMENTDATE AS TIMESTAMP) AS SETTLEMENTDATE,
    CAST(SETTLEMENTDATE AS DATE) AS DATE,
    CAST(YEAR(CAST(SETTLEMENTDATE AS TIMESTAMP)) AS INT16) AS YEAR
FROM raw